// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { GeoData } from '@/types/geoType'

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<GeoData[]>
) {
    res.status(200).json(JSON.parse(`[
        {
          "name": "Tokyo",
          "local_names": {
            "es": "Tokio",
            "da": "Tokyo",
            "mr": "तोक्यो",
            "th": "โตเกียว",
            "ia": "Tokyo",
            "ta": "டோக்கியோ",
            "he": "טוקיו",
            "zh": "东京都/東京都",
            "oc": "Tòquio",
            "is": "Tókýó",
            "ko": "도쿄도",
            "el": "Τόκιο",
            "mi": "Tōkio",
            "uk": "Токіо",
            "et": "Tōkyō",
            "hu": "Tokió",
            "bg": "Токио",
            "fi": "Tokio",
            "la": "Tokium",
            "kn": "ಟೋಕ್ಯೊ",
            "lb": "Tokio",
            "lv": "Tokija",
            "cs": "Tokio",
            "it": "Tokyo",
            "en": "Tokyo",
            "ca": "Tòquio",
            "tg": "Токио",
            "eo": "Tokio",
            "ru": "Токио",
            "hr": "Tokio",
            "be": "Токіа",
            "fa": "توکیو",
            "cy": "Tokyo",
            "vi": "Tokyo",
            "de": "Tokio",
            "io": "Tokyo",
            "tr": "Tokyo",
            "sl": "Tokio",
            "pt": "Tóquio",
            "ku": "Tokyo",
            "ar": "طوكيو",
            "pl": "Tokio",
            "sr": "Токио",
            "ja": "東京都",
            "fr": "Tokyo",
            "nl": "Tokio",
            "sv": "Tokyo",
            "sk": "Tokio",
            "lt": "Tokijas"
          },
          "lat": 35.6828387,
          "lon": 139.7594549,
          "country": "JP"
        },
        {
          "name": "Chofu",
          "local_names": {
            "gl": "Chōfu, Tōkyō",
            "bg": "Чофу",
            "nl": "Chofu",
            "sh": "Čofu",
            "et": "Chōfu",
            "ko": "조후시",
            "uk": "Тьофу",
            "pt": "Chofu",
            "it": "Chōfu",
            "sr": "Чофу",
            "ms": "Chofu",
            "zh": "調布市",
            "ja": "調布市",
            "ru": "Тёфу",
            "sv": "Chofu",
            "fi": "Chōfu",
            "es": "Chofu",
            "fa": "چوفو، توکیو",
            "pl": "Chōfu",
            "en": "Chofu",
            "lt": "Čiofu",
            "th": "โชฟุ",
            "ar": "تشوفو، طوكيو",
            "tg": "Чōфу",
            "fr": "Chōfu",
            "de": "Chōfu"
          },
          "lat": 35.660036,
          "lon": 139.554815,
          "country": "JP"
        },
        {
          "name": "Tama",
          "local_names": {
            "ru": "Тама",
            "pl": "Tama",
            "de": "Tama",
            "fi": "Tama",
            "sr": "Тама",
            "ja": "多摩市",
            "ms": "Tama",
            "ko": "다마시",
            "th": "ทามะ",
            "en": "Tama",
            "es": "Tama",
            "zh": "多摩市",
            "gl": "Tama, Tōkyō",
            "it": "Tama",
            "tg": "Тама",
            "lt": "Tama",
            "sh": "Tama",
            "nl": "Tama",
            "pt": "Tama",
            "ar": "تاما، طوكيو",
            "bg": "Тама",
            "uk": "Тама",
            "fa": "تاما، توکیو",
            "fr": "Tama"
          },
          "lat": 35.637188,
          "lon": 139.443503,
          "country": "JP"
        },
        {
          "name": "Kodaira",
          "local_names": {
            "sh": "Kodaira",
            "ru": "Кодайра",
            "pl": "Kodaira",
            "ro": "Kodaira, Tokyo",
            "ja": "小平市",
            "tl": "Kodaira, Tokyo",
            "gl": "Kodaira",
            "en": "Kodaira",
            "zh": "小平市",
            "fr": "Kodaira",
            "fa": "کودائیرا، توکیو",
            "bg": "Кодайра",
            "de": "Kodaira",
            "uk": "Кодайра",
            "tg": "Кодаира",
            "ar": "كودايرا، طوكيو",
            "ms": "Kodaira",
            "vi": "Kodaira, Tokyo",
            "pt": "Kodaira",
            "sr": "Кодаира",
            "eo": "Kodaira",
            "fi": "Kodaira",
            "it": "Kodaira",
            "es": "Kodaira",
            "th": "โคไดระ",
            "lt": "Kodaira",
            "ko": "고다이라시"
          },
          "lat": 35.72522,
          "lon": 139.476606,
          "country": "JP"
        },
        {
          "name": "Kokubunji",
          "local_names": {
            "en": "Kokubunji",
            "zh": "國分寺市",
            "de": "Kokubunji",
            "eo": "Kokubunĵi",
            "ru": "Кокубундзи",
            "sr": "Кокубунџи",
            "gl": "Kokubunji, Tōkyō",
            "it": "Kokubunji",
            "es": "Kokubunji",
            "pl": "Kokubunji",
            "fi": "Kokubunji",
            "uk": "Кокубундзі",
            "lt": "Kokubundžis",
            "pt": "Kokubunji",
            "sh": "Kokubunji",
            "tg": "Кокубунҷи",
            "ms": "Kokubunji",
            "ja": "国分寺市",
            "th": "โคกูบุนจิ",
            "ko": "고쿠분지시",
            "fa": "کوکوبونجی، توکیو",
            "fr": "Kokubunji",
            "ar": "كوكوبونجي، طوكيو"
          },
          "lat": 35.709674,
          "lon": 139.454224,
          "country": "JP"
        }
      ]`));
}